<a href="https://colab.research.google.com/github/lakithav/ml-internship-journey/blob/main/knn_algoritham.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [4]:
path ="/content/drive/MyDrive/DataSets/Iris.csv"
data = pd.read_csv(path)
data.head()
data.tail()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [6]:
data.shape

(150, 6)

In [9]:
data["Species"].value_counts()

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [13]:
data.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [14]:
x=data.iloc[:,1:5]
x.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2

In [15]:
y=data.iloc[:,-1]
y.head()

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Species, dtype: object

In [16]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [17]:
x=scaler.fit_transform(x)
x[0:5]

array([[-0.90068117,  1.03205722, -1.3412724 , -1.31297673],
       [-1.14301691, -0.1249576 , -1.3412724 , -1.31297673],
       [-1.38535265,  0.33784833, -1.39813811, -1.31297673],
       [-1.50652052,  0.10644536, -1.2844067 , -1.31297673],
       [-1.02184904,  1.26346019, -1.3412724 , -1.31297673]])

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [20]:
x_train.shape

(120, 4)

In [21]:
x_test.shape

(30, 4)

In [22]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=1)
model.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=1)

In [23]:
pred = model.predict(x_test)
pred[0:5]

array(['Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa'], dtype=object)

In [24]:
y_test[0:5]

90     Iris-versicolor
7          Iris-setosa
73     Iris-versicolor
132     Iris-virginica
31         Iris-setosa
Name: Species, dtype: object

In [25]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_test,pred)
accuracy

0.9666666666666667

In [26]:
result = pd.DataFrame(data=[y_test.values,pred], index=['y_test','pred'])
result.transpose()

             y_test             pred
0   Iris-versicolor  Iris-versicolor
1       Iris-setosa      Iris-setosa
2   Iris-versicolor  Iris-versicolor
3    Iris-virginica   Iris-virginica
4       Iris-setosa      Iris-setosa
5       Iris-setosa      Iris-setosa
6    Iris-virginica   Iris-virginica
7       Iris-setosa      Iris-setosa
8    Iris-virginica   Iris-virginica
9    Iris-virginica   Iris-virginica
10      Iris-setosa      Iris-setosa
11      Iris-setosa      Iris-setosa
12      Iris-setosa      Iris-setosa
13   Iris-virginica   Iris-virginica
14      Iris-setosa      Iris-setosa
15   Iris-virginica   Iris-virginica
16      Iris-setosa      Iris-setosa
17   Iris-virginica   Iris-virginica
18  Iris-versicolor  Iris-versicolor
19   Iris-virginica   Iris-virginica
20   Iris-virginica   Iris-virginica
21  Iris-versicolor  Iris-versicolor
22  Iris-versicolor  Iris-versicolor
23  Iris-versicolor  Iris-versicolor
24   Iris-virginica   Iris-virginica
25   Iris-virginica   Iris-virginica
26      Iris-setosa      Iris-setosa
27   Iris-virginica  Iris-versicolor
28  Iris-versicolor  Iris-versicolor
29   Iris-virginica   Iris-virginica

In [31]:
model=KNeighborsClassifier(n_neighbors=10)
model.fit(x_train,y_train)
pred=model.predict(x_test)

In [32]:
accuracy_score(y_test,pred)

0.9